name: flutter_flavorizr_demo
description: A demo to build white-label apps by utilizing flutter_flavorizr
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

flavorizr:
  ide: vscode
  flavors:
    apple:
      app:
        name: "Apple App"
      icon: "./assets/apple/apple.png"
      android:
        applicationId: "com.example.apple"
        customConfig:
          versionName: "\"1.0.0\"" 
      ios:
        bundleId: "com.example.apple"
        buildSettings: {
          FLUTTER_BUILD_NAME: "1.0.0"
        }

    banana:
      app:
        name: "Banana App"
        icon: "./assets/banana/banana.png"
      android:
        applicationId: "com.example.banana"
        customConfig:
          versionName: "\"1.0.1\"" 
      ios:
        bundleId: "com.example.banana"
        buildSettings: {
          FLUTTER_BUILD_NAME: "1.0.1"
        }

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.1.5

flutter:
  uses-material-design: true
